/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.christian.grafica_barras;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Christian Ramirez
 */
public class Barras extends javax.swing.JFrame {

    /**
     * Creates new form Barras
     */
    
    boolean estado = false;
    
    public Barras() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Grafico de Barras");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_promedio1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_promedio2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_promedio3 = new javax.swing.JTextField();
        btn_grafico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Grafico de Barras");

        jLabel1.setText("Digite el  1º promedio : ");

        jLabel2.setText("Digite el  2º promedio : ");

        jLabel3.setText("Digite el  3º promedio : ");

        btn_grafico.setText("Graficar");
        btn_grafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_graficoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_promedio3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_promedio2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_promedio1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btn_grafico, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txt_promedio1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_promedio2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_grafico, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_promedio3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(298, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_graficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_graficoActionPerformed
          estado = true;
          repaint();
    }//GEN-LAST:event_btn_graficoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_grafico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_promedio1;
    private javax.swing.JTextField txt_promedio2;
    private javax.swing.JTextField txt_promedio3;
    // End of variables declaration//GEN-END:variables

    //Creamos el metodo para hallar el maximo promedio
    public static int calcularMayorPromedio(int promedio1 , int promedio2 , int promedio3){
         if(promedio1 > promedio2 && promedio1 > promedio3){
             return  promedio1;
         }
         else if(promedio2 > promedio3){
             return promedio2;
         }
         else{
             return promedio3;
         }
    }
    
    //Creamos el metodo para graficar
    @Override
    public void paint(Graphics grafico){
        super.paint(grafico);
        
        try{
            if(estado == true){
                
                 String campo_promedio1 = txt_promedio1.getText();
                 String campo_promedio2 = txt_promedio2.getText();
                 String campo_promedio3 = txt_promedio3.getText();
                 
                 int valor_promedio1 = Integer.parseInt(campo_promedio1);
                 int valor_promedio2 = Integer.parseInt(campo_promedio2);
                 int valor_promedio3 = Integer.parseInt(campo_promedio3);
                 
                 int mayor_valor = calcularMayorPromedio(valor_promedio1,valor_promedio2,valor_promedio3);
                 
                 
                 int largo_promedio1 = valor_promedio1 * 400 / mayor_valor;
                 int largo_promedio2 = valor_promedio2 * 400 / mayor_valor;
                 int largo_promedio3 = valor_promedio3 * 400 / mayor_valor;
                 
                 
                 //Graficamos el promedio 1 o 1º promedio
                 grafico.setColor(Color.red);
                 grafico.fillRect(150,350,largo_promedio1,40);
                 grafico.drawString("1º promedio ",50,360);
                 
                 //Graficamos el promedio 2 o 2º promedio
                 grafico.setColor(Color.green);
                 grafico.fillRect(150,410,largo_promedio2,40);
                 grafico.drawString("2º promedio ",50,420);
                 
                 
                //Graficamos el promedio 3 o 3º promedio
                 grafico.setColor(Color.blue);
                 grafico.fillRect(150,470,largo_promedio3,40);
                 grafico.drawString("3º promedio ",50,480); 
            }           
        }catch(Exception e){
            System.out.println(e);
        }      
    }   
}
